title:            "@ssdr"
url:              http://ssdr.github.io
permalink:        /:year/:month/:title/

highlighter:      pygments

#markdown:         kramdown
#kramdown:
#  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

google_analytics: UA-21332781-7
timezone:         Asia/Shanghai
gems:
  - jemoji
  - jekyll-mentions
